name: Sync

on:
  push: # when this synchronizer update
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch: # on button click

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}"
  cancel-in-progress: true

jobs:
  sync-jdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'oraluben/jdk'
          token: ${{ secrets.UPDATE_TOKEN }}
          fetch-depth: 0
      - name: Add remotes
        run: |
          git remote add jdk https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/openjdk/jdk
          git remote add labs https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/graalvm/labs-openjdk
          git remote add loom https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/openjdk/loom
      - name: Fetch
        run: |
          git fetch --all --no-tags --shallow-since="1 day"
      - name: Push
        run: |
          git rebase jdk/master
          git push
          git checkout --track origin/fibers
          git rebase loom/fibers
          git push
          git checkout --track origin/labs
          git rebase labs/master
          git push
      - name: Sync tags from main
        run: |
          git fetch jdk --tags
          git push --tags
      - uses: gautamkrishnar/keepalive-workflow@v2
  sync-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'oraluben/node'
          token: ${{ secrets.UPDATE_TOKEN }}
          fetch-depth: 0
      - name: Add remotes
        run: |
          git remote add upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nodejs/node
      - name: Fetch
        run: |
          git fetch --all --no-tags --shallow-since="1 day"
      - name: Push
        run: |
          # git checkout --track origin/main
          git rebase upstream/main
          git push
  sync-graal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'oraluben/graal'
          token: ${{ secrets.UPDATE_TOKEN }}
          fetch-depth: 0
      - name: Add remotes
        run: |
          git remote add upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/oracle/graal
      - name: Fetch
        run: git fetch --all
      - name: Push
        run: |
          # git checkout --track origin/master
          git rebase upstream/master
          git push
          git push --tags
  sync-mx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'oraluben/mx'
          token: ${{ secrets.UPDATE_TOKEN }}
          fetch-depth: 0
      - name: Add remotes
        run: |
          git remote add upstream https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/graalvm/mx
      - name: Fetch
        run: git fetch --all
      - name: Push
        run: |
          # git checkout --track origin/master
          git rebase upstream/master
          git push
          git push --tags
  sync-cpython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'oraluben/cpython'
          token: ${{ secrets.UPDATE_TOKEN }}
          fetch-depth: 0
      - name: Add remotes
        run: |
          git remote add cpy https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/python/cpython
          git remote add pylbbv https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/pylbbv/pylbbv
      - name: Fetch
        run: |
          git fetch --all --no-tags --shallow-since="1 day"
      - name: Push
        run: |
          git rebase cpy/main
          git push
          git checkout --track origin/pylbbv
          git rebase pylbbv/pylbbv
          git push
